### ISSUE TITLE
np.stack error on complex numpy array

### ISSUE THREAD

**Issue by damienjacquet** [NeuroJSON/jdata#6]
to encode complex array, the np.stack method is used, but it results in the following error : 

File "C:\XXX\Lib\site-packages\jdata\jdata.py", line 136, in encode
    `newobj["_ArrayData_"] = np.stack(d.ravel().real, d.ravel().imag)`
TypeError: only integer scalar arrays can be converted to a scalar index

imaginary part is seen as the "axis" parameter of np.stack function. adding 2 parenthesis should fix the bug
`newobj["_ArrayData_"] = np.stack((d.ravel().real, d.ravel().imag))`

**Comment by fangq** [comment]
fixed in https://github.com/NeuroJSON/pyjdata/issues/3
